
/* Drop Tables */

DROP TABLE ACADEMIC CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE ANNUAL CASCADE CONSTRAINTS;
DROP TABLE BOOKMARK CASCADE CONSTRAINTS;
DROP TABLE CAREER CASCADE CONSTRAINTS;
DROP TABLE HISTORY CASCADE CONSTRAINTS;
DROP TABLE REFERENCE CASCADE CONSTRAINTS;
DROP TABLE RETIRE CASCADE CONSTRAINTS;
DROP TABLE SC_FILE CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE SDOC_LINE CASCADE CONSTRAINTS;
DROP TABLE DOC_FILE CASCADE CONSTRAINTS;
DROP TABLE SIGN_DOC CASCADE CONSTRAINTS;
DROP TABLE WORK_FILE CASCADE CONSTRAINTS;
DROP TABLE WORK_LINE CASCADE CONSTRAINTS;
DROP TABLE WORK CASCADE CONSTRAINTS;
DROP TABLE WORKLIST CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE DEPT CASCADE CONSTRAINTS;
DROP TABLE DOC_TYPE CASCADE CONSTRAINTS;
DROP TABLE HALFTIME CASCADE CONSTRAINTS;
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
DROP TABLE POSITION CASCADE CONSTRAINTS;
DROP TABLE TEAM CASCADE CONSTRAINTS;
DROP TABLE WORKTIME CASCADE CONSTRAINTS;
DROP TABLE WORK_TYPE CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_ACADEMIC;
DROP SEQUENCE SEQ_ACCOUNT;
DROP SEQUENCE SEQ_ANNUAL;
DROP SEQUENCE SEQ_BOOKMARK;
DROP SEQUENCE SEQ_CAREER;
DROP SEQUENCE SEQ_DEPT;
DROP SEQUENCE SEQ_DOC_FILE;
DROP SEQUENCE SEQ_DOC_FILE;
DROP SEQUENCE SEQ_DOC_TYPE;
DROP SEQUENCE SEQ_EMPLOYEE;
DROP SEQUENCE SEQ_HALFTIME;
DROP SEQUENCE SEQ_HALF_TIME;
DROP SEQUENCE SEQ_HISTORY;
DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_OFFICE;
DROP SEQUENCE SEQ_POSITION;
DROP SEQUENCE SEQ_REFERENCE;
DROP SEQUENCE SEQ_RETIRE;
DROP SEQUENCE SEQ_SCHEDULE;
DROP SEQUENCE SEQ_SC_FILE;
DROP SEQUENCE SEQ_SDOC_LINE;
DROP SEQUENCE SEQ_SIGN_DOC;
DROP SEQUENCE SEQ_TEAM;
DROP SEQUENCE SEQ_WORKLIST;
DROP SEQUENCE SEQ_WORKTIME;
DROP SEQUENCE SEQ_WORK_FILE;
DROP SEQUENCE SEQ_WORK_TYPE;
DROP SEQUENCE SEQ_WORK;




/* Create Sequences */

CREATE SEQUENCE SEQ_ACADEMIC INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_ACCOUNT INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_ANNUAL INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_BOOKMARK INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CAREER INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_DEPT INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_DOC_FILE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_DOC_FILE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_DOC_TYPE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_EMPLOYEE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_HALFTIME INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_HALF_TIME INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_HISTORY INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MESSAGE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_OFFICE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_POSITION INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_REFERENCE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_RETIRE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SCHEDULE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SC_FILE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SDOC_LINE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SIGN_DOC INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TEAM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_WORKLIST INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_WORKTIME INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_WORK_FILE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_WORK_TYPE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_WORK INCREMENT BY 1 START WITH 1;



/* Create Tables */

-- 학력테이블
CREATE TABLE ACADEMIC
(
	-- 학력번호 : 학력번호
	ACD_NUM number(10) NOT NULL,
	-- 졸업일 : 졸업일
	ACD_GRADUATION date,
	-- 학교명 : 학교명
	ACD_NAME varchar2(30),
	-- 전공 : 전공
	ACD_MAJOR varchar2(20),
	-- 학점 : 학점
	ACD_SCORE number(10,1),
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	PRIMARY KEY (ACD_NUM)
);


-- 계정테이블
CREATE TABLE ACCOUNT
(
	-- 계정번호 : 계정번호
	ACNT_NUM number(10) NOT NULL,
	-- 아이디 : 아이디
	ACNT_ID varchar2(20) NOT NULL,
	-- 비밀번호 : 비밀번호
	ACNT_PWD varchar2(20) NOT NULL,
	-- 권한레벨 : 권한레벨
	ACNT_LEVEL number(10) DEFAULT 1 NOT NULL,
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	PRIMARY KEY (ACNT_NUM)
);


-- 연차현황테이블
CREATE TABLE ANNUAL
(
	-- 연차번호 : 연차번호
	ANN_NUM number(10) NOT NULL,
	-- 전체연차수량 : 전체연차수량
	ANN_TOTAL number(10,1),
	-- 사용연차수량 : 사용연차수량
	ANN_USE number(10,1),
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	PRIMARY KEY (ANN_NUM)
);


-- 결재라인즐겨찾기테이블
CREATE TABLE BOOKMARK
(
	-- 북마크번호 : 북마크번호
	BKM_NUM number(10) NOT NULL,
	-- 결재순서 : 결재순서
	BKM_LEVEL number(10),
	-- 북마크이름 : 북마크이름
	BKM_NAME varchar2(20) NOT NULL,
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	PRIMARY KEY (BKM_NUM)
);


-- 경력테이블
CREATE TABLE CAREER
(
	-- 경력번호 : 경력번호
	CRR_NUM number(10) NOT NULL,
	-- 입사일 : 입사일
	CRR_SDATE date,
	-- 퇴사일 : 퇴사일
	CRR_EDATE date,
	-- 직장명 : 직장명
	CRR_NAME varchar2(20),
	-- 부서명 : 부서명
	CRR_DEPT varchar2(20),
	-- 직위 : 직위
	CRR_POSITION varchar2(15),
	-- 담당업무 : 담당업무
	CRR_WORK varchar2(30),
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	PRIMARY KEY (CRR_NUM)
);


-- 부서테이블
CREATE TABLE DEPT
(
	-- 부서번호 : 부서번호
	DEPT_NUM number(10) NOT NULL,
	-- 부서명 : 부서명
	DEPT_NAME varchar2(20),
	PRIMARY KEY (DEPT_NUM)
);


-- 결재문서파일테이블
CREATE TABLE DOC_FILE
(
	-- 결재파일번호 : 결재파일번호
	SFILE_NUM number(10) NOT NULL,
	-- 결재파일저장명 : 결재파일저장명
	SFILE_SAVEFILENAME varchar2(30),
	-- 결재저장파일명 : 결재저장파일명
	SFILE_ORGFILENAME varchar2(30),
	-- 결재파일크기 : 결재파일크기
	SFILE_SIZE long,
	-- 결재문서번호 : 결재문서번호
	SDOC_NUM number(10) NOT NULL,
	PRIMARY KEY (SFILE_NUM)
);


-- 결재문서종류테이블
CREATE TABLE DOC_TYPE
(
	-- 결재문서번호 : 결재문서번호
	DOC_NUM number(10) NOT NULL,
	-- 결재문서이름 : 결재문서이름(기안서,발주서,업무보고서...)
	DOC_NAME varchar2(30),
	PRIMARY KEY (DOC_NUM)
);


-- 사원개인정보테이블
CREATE TABLE EMPLOYEE
(
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	-- 사원이름 : 사원이름
	EMP_NAME varchar2(15) NOT NULL,
	-- 사원전화번호 : 사원전화번호
	EMP_PHONE varchar2(15),
	-- 사원주소 : 사원주소
	EMP_ADDR varchar2(60),
	-- 사원생년월일 : 사원생년월일
	EMP_BIRTH number(10),
	-- 사원이메일 : 사원이메일
	EMP_EMAIL varchar2(30) UNIQUE,
	-- 사원입사일 : 사원입사일
	EMP_HIREDATE date NOT NULL,
	-- 사원성별 : 사원성별
	EMP_GENDER varchar2(10),
	-- 직위번호 : 직위번호
	PST_NUM number(10) NOT NULL,
	-- 부서번호 : 부서번호
	DEPT_NUM number(10) NOT NULL,
	-- 팀번호 : 팀번호
	TEAM_NUM number(10) NOT NULL,
	PRIMARY KEY (EMP_NUM)
);


-- 반차지정테이블
CREATE TABLE HALFTIME
(
	-- 반차시간지정번호
	HTIME_NUM number(10) NOT NULL,
	-- 반차구분 : 0.오전
	-- 1.오후
	HTIME_TYPE number(5) NOT NULL,
	-- 시작시간
	HTIME_START date NOT NULL,
	-- 끝시간
	HTIME_END date NOT NULL,
	PRIMARY KEY (HTIME_NUM)
);


-- 근무이력테이블
CREATE TABLE HISTORY
(
	-- 근무이력번호 : 근무이력번호
	HIS_NUM number(10) NOT NULL,
	-- 날짜 : 날짜
	HIS_DATE date,
	-- 근무부서 : 근무부서
	HIS_DEPT varchar2(20),
	-- 직위 : 직위
	HIS_POSITION varchar2(15),
	-- 담당업무 : 담당업무
	HIS_WORK varchar2(20),
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	PRIMARY KEY (HIS_NUM)
);


-- 쪽지테이블
CREATE TABLE MESSAGE
(
	-- 쪽지번호 : 쪽지번호
	MSG_NUM number(10) NOT NULL,
	-- 받는사람아이디 : 받는사람아이디
	MSG_RECNAME varchar2(10),
	-- 보낸사람 : 보낸사람
	MSG_SENDNAME varchar2(30),
	-- 쪽지내용 : 쪽지내용
	MSG_CONTENT varchar2(100),
	-- 작성일 : 작성일
	MSG_REGDATE date,
	-- 쪽지 수신여부 구분 : 0.안읽음
	-- 1.읽음
	MSG_TYPE number(5),
	PRIMARY KEY (MSG_NUM)
);


-- 직위테이블
CREATE TABLE POSITION
(
	-- 직위번호 : 직위번호
	PST_NUM number(10) NOT NULL,
	-- 직위명 : 직위명
	PST_NAME varchar2(20),
	PRIMARY KEY (PST_NUM)
);


-- 결재참조테이블
CREATE TABLE REFERENCE
(
	-- 참조번호 : 참조번호
	REF_NUM number(10) NOT NULL,
	-- 결재문서번호 : 결재문서번호
	SDOC_NUM number(10) NOT NULL,
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	PRIMARY KEY (REF_NUM)
);


-- 퇴직자테이블
CREATE TABLE RETIRE
(
	-- 퇴직자번호 : 퇴직자번호
	RE_NUM number(10) NOT NULL,
	-- 퇴직일
	RE_DATE date NOT NULL,
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	PRIMARY KEY (RE_NUM)
);


-- 일정테이블
CREATE TABLE SCHEDULE
(
	-- 일정번호 : 일정번호
	SCH_NUM number(10) NOT NULL,
	-- 일정이름 : 일정이름
	SCH_TITLE varchar2(30) NOT NULL,
	-- 일정내용 : 일정내용
	SCH_CONTENT varchar2(100),
	-- 시작일 : 시작일
	SCH_SDATE date,
	-- 종료일 : 종료일
	SCH_EDATE date,
	-- 일정장소 : 일정장소
	SCH_PLACE varchar2(20),
	-- 공개여부 : 공개여부
	SCH_PUBLIC number(10),
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	PRIMARY KEY (SCH_NUM)
);


-- 일정파일테이블
CREATE TABLE SC_FILE
(
	-- 일정파일번호 : 일정파일번호
	SF_NUM number(10) NOT NULL,
	-- 일정파일저장명 : 일정파일저장명
	SF_SAVEFILENAME varchar2(30),
	-- 일정원본파일명 : 일정원본파일명
	SF_ORGFILENAME varchar2(30),
	-- 일정파일크기 : 일정파일크기
	SF_SIZE long,
	-- 일정번호 : 일정번호
	SCH_NUM number(10) NOT NULL,
	PRIMARY KEY (SF_NUM)
);


-- 결재라인테이블
CREATE TABLE SDOC_LINE
(
	-- 결재라인번호 : 결재라인번호
	SLINE_NUM number(10) NOT NULL,
	-- 결재순서 : 결재순서
	SLINE_LEVEL number(10),
	-- 결재상태 : 결재상태
	SLINE_STATE number(10),
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	-- 결재문서번호 : 결재문서번호
	SDOC_NUM number(10) NOT NULL,
	PRIMARY KEY (SLINE_NUM)
);


-- 결재문서테이블
CREATE TABLE SIGN_DOC
(
	-- 결재문서번호 : 결재문서번호
	SDOC_NUM number(10) NOT NULL,
	-- 문서결재상태 : 문서결재상태
	SDOC_STATE number(10) DEFAULT 1 NOT NULL,
	-- 결재문서제목 : 결재문서제목
	SDOC_TITLE varchar2(30),
	-- 결재문서내용 : 결재문서내용
	SDOC_CONTENT clob,
	-- 결재문서 작성일
	SDOC_DATE date,
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	-- 결재문서번호 : 결재문서번호
	DOC_NUM number(10) NOT NULL,
	PRIMARY KEY (SDOC_NUM)
);


-- 조직도테이블
CREATE TABLE TEAM
(
	-- 팀번호 : 팀번호
	TEAM_NUM number(10) NOT NULL,
	-- 팀이름 : 팀이름
	TEAM_NAME varchar2(20),
	PRIMARY KEY (TEAM_NUM)
);


-- 연차신청현황테이블
CREATE TABLE WORK
(
	-- 연차신청번호 : 연차신청번호
	WORK_NUM number(10) NOT NULL,
	-- 시작일 : 시작일
	WORK_SDATE date,
	-- 종료일 : 종료일
	WORK_EDATE date,
	-- 연차사유 : 연차사유
	WORK_CONTENT varchar2(100),
	-- 등록일 : 등록일
	WORK_REGDATE date NOT NULL,
	-- 연차승인상태 : 연차승인상태
	WORK_STATE number(10) DEFAULT 1 NOT NULL,
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	-- 연차구분번호 : 연차구분번호
	WTYPE_NUM number(10) NOT NULL,
	PRIMARY KEY (WORK_NUM)
);


-- 출퇴근내역
CREATE TABLE WORKLIST
(
	-- 출퇴근내역번호 : 출퇴근내역번호
	WLIST_NUM number(10) NOT NULL,
	-- 출근시간 : 출근시간
	WLIST_START date,
	-- 퇴근시간 : 퇴근시간
	WLIST_END date,
	-- 외출출발시간 : 외출출발시간
	WLIST_GO date,
	-- 외출복귀시간 : 외출복귀시간
	WLIST_BACK date,
	-- 출퇴근상태(결근포함) : 0.출근
	-- 1.결근
	-- 2.조퇴
	-- 3.지각
	-- 4.연차
	-- 5.반차
	WLIST_TYPE number(5),
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	PRIMARY KEY (WLIST_NUM)
);


-- 출퇴근지정테이블
CREATE TABLE WORKTIME
(
	-- 출퇴근지정번호 : 출퇴근지정번호
	WTIME_NUM number(10) NOT NULL,
	-- 출근시간지정 : 출근시간지정
	WTIME_START date,
	-- 퇴근시간지정 : 퇴근시간지정
	WTIME_END date,
	PRIMARY KEY (WTIME_NUM)
);


-- 근태파일테이블
CREATE TABLE WORK_FILE
(
	-- 근태문서파일번호 : 결재문서파일번호
	WFILE_NUM number(10) NOT NULL,
	-- 근태문서 파일저장명 : 결재문서 파일저장명
	WFILE_SAVEFILENAME varchar2(30),
	-- 근태문서 원본파일명 : 결재문서 원본파일명
	WFILE_ORGFILENAME varchar2(30),
	-- 근태문서 파일크기 : 결재문서 파일크기
	WFILE_SIZE long,
	-- 연차신청번호 : 연차신청번호
	WORK_NUM number(10) NOT NULL,
	PRIMARY KEY (WFILE_NUM)
);


-- 근태라인테이블
CREATE TABLE WORK_LINE
(
	-- 근태라인번호 : 결재라인번호
	WLINE_NUM number(10) NOT NULL,
	-- 근태결재순서 : 결재순서
	WLINE_LEVEL number(10),
	-- 결재상태 : 결재상태
	-- 0이 반려
	-- 1이 승인
	WLINE_STATE number(10),
	-- 연차신청번호 : 연차신청번호
	WORK_NUM number(10) NOT NULL,
	-- 사원번호 : 사원번호
	EMP_NUM number(10) NOT NULL UNIQUE,
	PRIMARY KEY (WLINE_NUM)
);


-- 연차구분테이블
CREATE TABLE WORK_TYPE
(
	-- 연차구분번호 : 연차구분번호
	WTYPE_NUM number(10) NOT NULL,
	-- 연차구분명 : 연차구분명
	WTYPE_NAME varchar2(15) NOT NULL,
	PRIMARY KEY (WTYPE_NUM)
);



/* Create Foreign Keys */

ALTER TABLE EMPLOYEE
	ADD FOREIGN KEY (DEPT_NUM)
	REFERENCES DEPT (DEPT_NUM)
;


ALTER TABLE SIGN_DOC
	ADD FOREIGN KEY (DOC_NUM)
	REFERENCES DOC_TYPE (DOC_NUM)
;


ALTER TABLE ACADEMIC
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE ACCOUNT
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE ANNUAL
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE BOOKMARK
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE CAREER
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE HISTORY
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE REFERENCE
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE RETIRE
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE SCHEDULE
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE SDOC_LINE
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE SIGN_DOC
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE WORK
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE WORKLIST
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE WORK_LINE
	ADD FOREIGN KEY (EMP_NUM)
	REFERENCES EMPLOYEE (EMP_NUM)
;


ALTER TABLE EMPLOYEE
	ADD FOREIGN KEY (PST_NUM)
	REFERENCES POSITION (PST_NUM)
;


ALTER TABLE SC_FILE
	ADD FOREIGN KEY (SCH_NUM)
	REFERENCES SCHEDULE (SCH_NUM)
;


ALTER TABLE DOC_FILE
	ADD FOREIGN KEY (SDOC_NUM)
	REFERENCES SIGN_DOC (SDOC_NUM)
;


ALTER TABLE REFERENCE
	ADD FOREIGN KEY (SDOC_NUM)
	REFERENCES SIGN_DOC (SDOC_NUM)
;


ALTER TABLE SDOC_LINE
	ADD FOREIGN KEY (SDOC_NUM)
	REFERENCES SIGN_DOC (SDOC_NUM)
;


ALTER TABLE EMPLOYEE
	ADD FOREIGN KEY (TEAM_NUM)
	REFERENCES TEAM (TEAM_NUM)
;


ALTER TABLE WORK_FILE
	ADD FOREIGN KEY (WORK_NUM)
	REFERENCES WORK (WORK_NUM)
;


ALTER TABLE WORK_LINE
	ADD FOREIGN KEY (WORK_NUM)
	REFERENCES WORK (WORK_NUM)
;


ALTER TABLE WORK
	ADD FOREIGN KEY (WTYPE_NUM)
	REFERENCES WORK_TYPE (WTYPE_NUM)
;



/* Comments */

COMMENT ON TABLE ACADEMIC IS '학력테이블';
COMMENT ON COLUMN ACADEMIC.ACD_NUM IS '학력번호 : 학력번호';
COMMENT ON COLUMN ACADEMIC.ACD_GRADUATION IS '졸업일 : 졸업일';
COMMENT ON COLUMN ACADEMIC.ACD_NAME IS '학교명 : 학교명';
COMMENT ON COLUMN ACADEMIC.ACD_MAJOR IS '전공 : 전공';
COMMENT ON COLUMN ACADEMIC.ACD_SCORE IS '학점 : 학점';
COMMENT ON COLUMN ACADEMIC.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON TABLE ACCOUNT IS '계정테이블';
COMMENT ON COLUMN ACCOUNT.ACNT_NUM IS '계정번호 : 계정번호';
COMMENT ON COLUMN ACCOUNT.ACNT_ID IS '아이디 : 아이디';
COMMENT ON COLUMN ACCOUNT.ACNT_PWD IS '비밀번호 : 비밀번호';
COMMENT ON COLUMN ACCOUNT.ACNT_LEVEL IS '권한레벨 : 권한레벨';
COMMENT ON COLUMN ACCOUNT.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON TABLE ANNUAL IS '연차현황테이블';
COMMENT ON COLUMN ANNUAL.ANN_NUM IS '연차번호 : 연차번호';
COMMENT ON COLUMN ANNUAL.ANN_TOTAL IS '전체연차수량 : 전체연차수량';
COMMENT ON COLUMN ANNUAL.ANN_USE IS '사용연차수량 : 사용연차수량';
COMMENT ON COLUMN ANNUAL.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON TABLE BOOKMARK IS '결재라인즐겨찾기테이블';
COMMENT ON COLUMN BOOKMARK.BKM_NUM IS '북마크번호 : 북마크번호';
COMMENT ON COLUMN BOOKMARK.BKM_LEVEL IS '결재순서 : 결재순서';
COMMENT ON COLUMN BOOKMARK.BKM_NAME IS '북마크이름 : 북마크이름';
COMMENT ON COLUMN BOOKMARK.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON TABLE CAREER IS '경력테이블';
COMMENT ON COLUMN CAREER.CRR_NUM IS '경력번호 : 경력번호';
COMMENT ON COLUMN CAREER.CRR_SDATE IS '입사일 : 입사일';
COMMENT ON COLUMN CAREER.CRR_EDATE IS '퇴사일 : 퇴사일';
COMMENT ON COLUMN CAREER.CRR_NAME IS '직장명 : 직장명';
COMMENT ON COLUMN CAREER.CRR_DEPT IS '부서명 : 부서명';
COMMENT ON COLUMN CAREER.CRR_POSITION IS '직위 : 직위';
COMMENT ON COLUMN CAREER.CRR_WORK IS '담당업무 : 담당업무';
COMMENT ON COLUMN CAREER.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON TABLE DEPT IS '부서테이블';
COMMENT ON COLUMN DEPT.DEPT_NUM IS '부서번호 : 부서번호';
COMMENT ON COLUMN DEPT.DEPT_NAME IS '부서명 : 부서명';
COMMENT ON TABLE DOC_FILE IS '결재문서파일테이블';
COMMENT ON COLUMN DOC_FILE.SFILE_NUM IS '결재파일번호 : 결재파일번호';
COMMENT ON COLUMN DOC_FILE.SFILE_SAVEFILENAME IS '결재파일저장명 : 결재파일저장명';
COMMENT ON COLUMN DOC_FILE.SFILE_ORGFILENAME IS '결재저장파일명 : 결재저장파일명';
COMMENT ON COLUMN DOC_FILE.SFILE_SIZE IS '결재파일크기 : 결재파일크기';
COMMENT ON COLUMN DOC_FILE.SDOC_NUM IS '결재문서번호 : 결재문서번호';
COMMENT ON TABLE DOC_TYPE IS '결재문서종류테이블';
COMMENT ON COLUMN DOC_TYPE.DOC_NUM IS '결재문서번호 : 결재문서번호';
COMMENT ON COLUMN DOC_TYPE.DOC_NAME IS '결재문서이름 : 결재문서이름(기안서,발주서,업무보고서...)';
COMMENT ON TABLE EMPLOYEE IS '사원개인정보테이블';
COMMENT ON COLUMN EMPLOYEE.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON COLUMN EMPLOYEE.EMP_NAME IS '사원이름 : 사원이름';
COMMENT ON COLUMN EMPLOYEE.EMP_PHONE IS '사원전화번호 : 사원전화번호';
COMMENT ON COLUMN EMPLOYEE.EMP_ADDR IS '사원주소 : 사원주소';
COMMENT ON COLUMN EMPLOYEE.EMP_BIRTH IS '사원생년월일 : 사원생년월일';
COMMENT ON COLUMN EMPLOYEE.EMP_EMAIL IS '사원이메일 : 사원이메일';
COMMENT ON COLUMN EMPLOYEE.EMP_HIREDATE IS '사원입사일 : 사원입사일';
COMMENT ON COLUMN EMPLOYEE.EMP_GENDER IS '사원성별 : 사원성별';
COMMENT ON COLUMN EMPLOYEE.PST_NUM IS '직위번호 : 직위번호';
COMMENT ON COLUMN EMPLOYEE.DEPT_NUM IS '부서번호 : 부서번호';
COMMENT ON COLUMN EMPLOYEE.TEAM_NUM IS '팀번호 : 팀번호';
COMMENT ON TABLE HALFTIME IS '반차지정테이블';
COMMENT ON COLUMN HALFTIME.HTIME_NUM IS '반차시간지정번호';
COMMENT ON COLUMN HALFTIME.HTIME_TYPE IS '반차구분 : 0.오전
1.오후';
COMMENT ON COLUMN HALFTIME.HTIME_START IS '시작시간';
COMMENT ON COLUMN HALFTIME.HTIME_END IS '끝시간';
COMMENT ON TABLE HISTORY IS '근무이력테이블';
COMMENT ON COLUMN HISTORY.HIS_NUM IS '근무이력번호 : 근무이력번호';
COMMENT ON COLUMN HISTORY.HIS_DATE IS '날짜 : 날짜';
COMMENT ON COLUMN HISTORY.HIS_DEPT IS '근무부서 : 근무부서';
COMMENT ON COLUMN HISTORY.HIS_POSITION IS '직위 : 직위';
COMMENT ON COLUMN HISTORY.HIS_WORK IS '담당업무 : 담당업무';
COMMENT ON COLUMN HISTORY.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON TABLE MESSAGE IS '쪽지테이블';
COMMENT ON COLUMN MESSAGE.MSG_NUM IS '쪽지번호 : 쪽지번호';
COMMENT ON COLUMN MESSAGE.MSG_RECNAME IS '받는사람아이디 : 받는사람아이디';
COMMENT ON COLUMN MESSAGE.MSG_SENDNAME IS '보낸사람 : 보낸사람';
COMMENT ON COLUMN MESSAGE.MSG_CONTENT IS '쪽지내용 : 쪽지내용';
COMMENT ON COLUMN MESSAGE.MSG_REGDATE IS '작성일 : 작성일';
COMMENT ON COLUMN MESSAGE.MSG_TYPE IS '쪽지 수신여부 구분 : 0.안읽음
1.읽음';
COMMENT ON TABLE POSITION IS '직위테이블';
COMMENT ON COLUMN POSITION.PST_NUM IS '직위번호 : 직위번호';
COMMENT ON COLUMN POSITION.PST_NAME IS '직위명 : 직위명';
COMMENT ON TABLE REFERENCE IS '결재참조테이블';
COMMENT ON COLUMN REFERENCE.REF_NUM IS '참조번호 : 참조번호';
COMMENT ON COLUMN REFERENCE.SDOC_NUM IS '결재문서번호 : 결재문서번호';
COMMENT ON COLUMN REFERENCE.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON TABLE RETIRE IS '퇴직자테이블';
COMMENT ON COLUMN RETIRE.RE_NUM IS '퇴직자번호 : 퇴직자번호';
COMMENT ON COLUMN RETIRE.RE_DATE IS '퇴직일';
COMMENT ON COLUMN RETIRE.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON TABLE SCHEDULE IS '일정테이블';
COMMENT ON COLUMN SCHEDULE.SCH_NUM IS '일정번호 : 일정번호';
COMMENT ON COLUMN SCHEDULE.SCH_TITLE IS '일정이름 : 일정이름';
COMMENT ON COLUMN SCHEDULE.SCH_CONTENT IS '일정내용 : 일정내용';
COMMENT ON COLUMN SCHEDULE.SCH_SDATE IS '시작일 : 시작일';
COMMENT ON COLUMN SCHEDULE.SCH_EDATE IS '종료일 : 종료일';
COMMENT ON COLUMN SCHEDULE.SCH_PLACE IS '일정장소 : 일정장소';
COMMENT ON COLUMN SCHEDULE.SCH_PUBLIC IS '공개여부 : 공개여부';
COMMENT ON COLUMN SCHEDULE.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON TABLE SC_FILE IS '일정파일테이블';
COMMENT ON COLUMN SC_FILE.SF_NUM IS '일정파일번호 : 일정파일번호';
COMMENT ON COLUMN SC_FILE.SF_SAVEFILENAME IS '일정파일저장명 : 일정파일저장명';
COMMENT ON COLUMN SC_FILE.SF_ORGFILENAME IS '일정원본파일명 : 일정원본파일명';
COMMENT ON COLUMN SC_FILE.SF_SIZE IS '일정파일크기 : 일정파일크기';
COMMENT ON COLUMN SC_FILE.SCH_NUM IS '일정번호 : 일정번호';
COMMENT ON TABLE SDOC_LINE IS '결재라인테이블';
COMMENT ON COLUMN SDOC_LINE.SLINE_NUM IS '결재라인번호 : 결재라인번호';
COMMENT ON COLUMN SDOC_LINE.SLINE_LEVEL IS '결재순서 : 결재순서';
COMMENT ON COLUMN SDOC_LINE.SLINE_STATE IS '결재상태 : 결재상태';
COMMENT ON COLUMN SDOC_LINE.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON COLUMN SDOC_LINE.SDOC_NUM IS '결재문서번호 : 결재문서번호';
COMMENT ON TABLE SIGN_DOC IS '결재문서테이블';
COMMENT ON COLUMN SIGN_DOC.SDOC_NUM IS '결재문서번호 : 결재문서번호';
COMMENT ON COLUMN SIGN_DOC.SDOC_STATE IS '문서결재상태 : 문서결재상태';
COMMENT ON COLUMN SIGN_DOC.SDOC_TITLE IS '결재문서제목 : 결재문서제목';
COMMENT ON COLUMN SIGN_DOC.SDOC_CONTENT IS '결재문서내용 : 결재문서내용';
COMMENT ON COLUMN SIGN_DOC.SDOC_DATE IS '결재문서 작성일';
COMMENT ON COLUMN SIGN_DOC.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON COLUMN SIGN_DOC.DOC_NUM IS '결재문서번호 : 결재문서번호';
COMMENT ON TABLE TEAM IS '조직도테이블';
COMMENT ON COLUMN TEAM.TEAM_NUM IS '팀번호 : 팀번호';
COMMENT ON COLUMN TEAM.TEAM_NAME IS '팀이름 : 팀이름';
COMMENT ON TABLE WORK IS '연차신청현황테이블';
COMMENT ON COLUMN WORK.WORK_NUM IS '연차신청번호 : 연차신청번호';
COMMENT ON COLUMN WORK.WORK_SDATE IS '시작일 : 시작일';
COMMENT ON COLUMN WORK.WORK_EDATE IS '종료일 : 종료일';
COMMENT ON COLUMN WORK.WORK_CONTENT IS '연차사유 : 연차사유';
COMMENT ON COLUMN WORK.WORK_REGDATE IS '등록일 : 등록일';
COMMENT ON COLUMN WORK.WORK_STATE IS '연차승인상태 : 연차승인상태';
COMMENT ON COLUMN WORK.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON COLUMN WORK.WTYPE_NUM IS '연차구분번호 : 연차구분번호';
COMMENT ON TABLE WORKLIST IS '출퇴근내역';
COMMENT ON COLUMN WORKLIST.WLIST_NUM IS '출퇴근내역번호 : 출퇴근내역번호';
COMMENT ON COLUMN WORKLIST.WLIST_START IS '출근시간 : 출근시간';
COMMENT ON COLUMN WORKLIST.WLIST_END IS '퇴근시간 : 퇴근시간';
COMMENT ON COLUMN WORKLIST.WLIST_GO IS '외출출발시간 : 외출출발시간';
COMMENT ON COLUMN WORKLIST.WLIST_BACK IS '외출복귀시간 : 외출복귀시간
';
COMMENT ON COLUMN WORKLIST.WLIST_TYPE IS '출퇴근상태(결근포함) : 0.출근
1.결근
2.조퇴
3.지각
4.연차
5.반차
';
COMMENT ON COLUMN WORKLIST.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON TABLE WORKTIME IS '출퇴근지정테이블';
COMMENT ON COLUMN WORKTIME.WTIME_NUM IS '출퇴근지정번호 : 출퇴근지정번호';
COMMENT ON COLUMN WORKTIME.WTIME_START IS '출근시간지정 : 출근시간지정';
COMMENT ON COLUMN WORKTIME.WTIME_END IS '퇴근시간지정 : 퇴근시간지정';
COMMENT ON TABLE WORK_FILE IS '근태파일테이블';
COMMENT ON COLUMN WORK_FILE.WFILE_NUM IS '근태문서파일번호 : 결재문서파일번호';
COMMENT ON COLUMN WORK_FILE.WFILE_SAVEFILENAME IS '근태문서 파일저장명 : 결재문서 파일저장명';
COMMENT ON COLUMN WORK_FILE.WFILE_ORGFILENAME IS '근태문서 원본파일명 : 결재문서 원본파일명';
COMMENT ON COLUMN WORK_FILE.WFILE_SIZE IS '근태문서 파일크기 : 결재문서 파일크기';
COMMENT ON COLUMN WORK_FILE.WORK_NUM IS '연차신청번호 : 연차신청번호';
COMMENT ON TABLE WORK_LINE IS '근태라인테이블';
COMMENT ON COLUMN WORK_LINE.WLINE_NUM IS '근태라인번호 : 결재라인번호';
COMMENT ON COLUMN WORK_LINE.WLINE_LEVEL IS '근태결재순서 : 결재순서';
COMMENT ON COLUMN WORK_LINE.WLINE_STATE IS '결재상태 : 결재상태
0이 반려
1이 승인';
COMMENT ON COLUMN WORK_LINE.WORK_NUM IS '연차신청번호 : 연차신청번호';
COMMENT ON COLUMN WORK_LINE.EMP_NUM IS '사원번호 : 사원번호';
COMMENT ON TABLE WORK_TYPE IS '연차구분테이블';
COMMENT ON COLUMN WORK_TYPE.WTYPE_NUM IS '연차구분번호 : 연차구분번호';
COMMENT ON COLUMN WORK_TYPE.WTYPE_NAME IS '연차구분명 : 연차구분명';


